### PR TITLE
add alpha parameter

### PR DESCRIPTION
**Pull request by harrisonritz**
takes argument for colormap opacity. Will break if alpha < 0, but doc + error is informative.

### CODE REVIEW

**Comment by danjgale** [comment]
Hey @harrisonritz I'm _finally_ getting around to this, and have spotted a few bugs that need fixes. Given that you submitted this awhile ago, if it's alright with you I can just add in the fixes directly to this PR rather than reviewing + making you add them. Lmk

**Comment by harrisonritz** [comment]
Sweet! Ya, feel free to add yourself, don’t need to keep me in the loop.


Harrison

From: Dan Gale ***@***.***>
Date: Monday, December 19, 2022 at 12:19 PM
To: danjgale/surfplot ***@***.***>
Cc: Harrison Ritz ***@***.***>, Mention ***@***.***>
Subject: Re: [danjgale/surfplot] add alpha parameter (PR #14)

Hey @harrisonritz<https://github.com/harrisonritz> I'm finally getting around to this, and have spotted a few bugs that need fixes. Given that you submitted this awhile ago, if it's alright with you I can just add in the fixes directly to this PR rather than reviewing + making you add them. Lmk

**Comment by danjgale** [comment]
Great thanks! Can you click "Allow edits from maintainers"?

**Comment by harrisonritz** [comment]
looks like this is checked already.

**Comment by danjgale** [comment]
All looks good now. Thanks for your contribution @harrisonritz!

**Comment by harrisonritz** [comment]
np! sorry for being shit at python haha the colons kill me

**Pull request merged**
